// Include gulp
var gulp = require('gulp');



// Include Our Plugins
//var jshint = require('gulp-jshint');
var sass = require('gulp-sass');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');

//var compress = require('gulp-yuicompressor');
 



// Lint Task
gulp.task('lint', function() {
    return gulp.src('js/*.js')
        .pipe(jshint())
        .pipe(jshint.reporter('default'));
});

// Compile Our Sass
gulp.task('sass', function() {
    return gulp.src('scss/*.scss')
        .pipe(sass())
        .pipe(gulp.dest('dist/css'));
});

// Concatenate & Minify JS
gulp.task('scripts', function() {
    return gulp.src('js/*.js')
        .pipe(concat('all.js'))
        .pipe(gulp.dest('dist'))
        .pipe(rename('all.min.js'))
        .pipe(uglify())
        .pipe(gulp.dest('dist/js'));
});


// Concatenate & Minify JS
gulp.task('mjg', function() {
	return gulp.src([
			'Boot.js',
			'ext-6.2.0.940/packages/core/src/Ext.js',
			'ext-6.2.0.940/modern/modern/overrides/init.js',
			'ext-6.2.0.940/packages/core/src/lang/Error.js',
			'ext-6.2.0.940/packages/core/src/lang/Array.js',
			'ext-6.2.0.940/packages/core/src/lang/Assert.js',
			'ext-6.2.0.940/packages/core/src/lang/String.js',
			'ext-6.2.0.940/packages/core/src/lang/Date.js',
			'ext-6.2.0.940/packages/core/src/lang/Function.js',
			'ext-6.2.0.940/packages/core/src/lang/Number.js',
			'ext-6.2.0.940/packages/core/src/lang/Object.js',
			'ext-6.2.0.940/packages/core/src/Util.js',
			'ext-6.2.0.940/packages/core/src/util/Version.js',
			'ext-6.2.0.940/packages/core/src/class/Config.js',
			'ext-6.2.0.940/packages/core/src/class/Configurator.js',
			'ext-6.2.0.940/packages/core/src/class/Base.js',
			'ext-6.2.0.940/packages/core/src/util/Cache.js',
			'ext-6.2.0.940/packages/core/src/class/Class.js',
			'ext-6.2.0.940/packages/core/src/class/Inventory.js',
			'ext-6.2.0.940/packages/core/src/class/ClassManager.js',
			'ext-6.2.0.940/packages/core/src/env/Browser.js',
			'ext-6.2.0.940/packages/core/src/env/OS.js',
			'ext-6.2.0.940/packages/core/src/env/Feature.js',
			'ext-6.2.0.940/packages/core/src/env/Ready.js',
			'ext-6.2.0.940/packages/core/src/class/Loader.js',
			'ext-6.2.0.940/packages/core/src/class/Mixin.js',
			'ext-6.2.0.940/packages/core/src/util/DelayedTask.js',
			'ext-6.2.0.940/packages/core/src/util/Event.js',
			'ext-6.2.0.940/packages/core/src/mixin/Identifiable.js',
			'ext-6.2.0.940/packages/core/src/mixin/Observable.js',
			'ext-6.2.0.940/packages/core/src/util/HashMap.js',
			'ext-6.2.0.940/packages/core/src/AbstractManager.js',
			'ext-6.2.0.940/packages/core/src/promise/Consequence.js',
			'ext-6.2.0.940/packages/core/src/promise/Deferred.js',
			'ext-6.2.0.940/packages/core/src/promise/Promise.js',
			'ext-6.2.0.940/packages/core/src/Promise.js',
			'ext-6.2.0.940/packages/core/src/Deferred.js',
			'ext-6.2.0.940/packages/core/src/mixin/Factoryable.js',
			'ext-6.2.0.940/packages/core/src/data/request/Base.js',
			'ext-6.2.0.940/packages/core/src/data/flash/BinaryXhr.js',
			'ext-6.2.0.940/packages/core/src/data/request/Ajax.js',
			'ext-6.2.0.940/packages/core/src/data/request/Form.js',
			'ext-6.2.0.940/packages/core/src/data/Connection.js',
			'ext-6.2.0.940/packages/core/src/Ajax.js',
			'ext-6.2.0.940/packages/core/src/AnimationQueue.js',
			'ext-6.2.0.940/packages/core/src/ComponentManager.js',
			'ext-6.2.0.940/packages/core/src/util/Operators.js',
			'ext-6.2.0.940/packages/core/src/util/LruCache.js',
			'ext-6.2.0.940/packages/core/src/ComponentQuery.js',
			'ext-6.2.0.940/packages/core/src/Evented.js',
			'ext-6.2.0.940/packages/core/src/util/Positionable.js',
			'ext-6.2.0.940/packages/core/src/dom/UnderlayPool.js',
			'ext-6.2.0.940/packages/core/src/dom/Underlay.js',
			'ext-6.2.0.940/packages/core/src/dom/Shadow.js',
			'ext-6.2.0.940/packages/core/src/dom/Shim.js',
			'ext-6.2.0.940/packages/core/src/dom/ElementEvent.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/Publisher.js',
			'ext-6.2.0.940/packages/core/src/util/Offset.js',
			'ext-6.2.0.940/packages/core/src/util/Region.js',
			'ext-6.2.0.940/packages/core/src/util/Point.js',
			'ext-6.2.0.940/packages/core/src/event/Event.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/Dom.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/Gesture.js',
			'ext-6.2.0.940/packages/core/src/mixin/Templatable.js',
			'ext-6.2.0.940/packages/core/src/TaskQueue.js',
			'ext-6.2.0.940/packages/core/src/util/sizemonitor/Abstract.js',
			'ext-6.2.0.940/packages/core/src/util/sizemonitor/Scroll.js',
			'ext-6.2.0.940/packages/core/src/util/sizemonitor/OverflowChange.js',
			'ext-6.2.0.940/packages/core/src/util/SizeMonitor.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/ElementSize.js',
			'ext-6.2.0.940/packages/core/src/util/paintmonitor/Abstract.js',
			'ext-6.2.0.940/packages/core/src/util/paintmonitor/CssAnimation.js',
			'ext-6.2.0.940/packages/core/src/util/PaintMonitor.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/ElementPaint.js',
			'ext-6.2.0.940/packages/core/src/dom/Element.js',
			'ext-6.2.0.940/modern/modern/overrides/dom/Element.js',
			'ext-6.2.0.940/packages/core/src/GlobalEvents.js',
			'ext-6.2.0.940/packages/core/src/Glyph.js',
			'ext-6.2.0.940/packages/core/src/JSON.js',
			'ext-6.2.0.940/packages/core/src/mixin/Inheritable.js',
			'ext-6.2.0.940/packages/core/src/mixin/Bindable.js',
			'ext-6.2.0.940/packages/core/src/mixin/ComponentDelegation.js',
			'ext-6.2.0.940/packages/core/src/mixin/Pluggable.js',
			'ext-6.2.0.940/packages/core/src/Widget.js',
			'ext-6.2.0.940/packages/core/src/mixin/Traversable.js',
			'ext-6.2.0.940/modern/modern/src/behavior/Behavior.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/Abstract.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/Linear.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/Abstract.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/Dom.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/CssTransform.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/ScrollPosition.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/ScrollParent.js',
			'ext-6.2.0.940/packages/core/src/util/translatable/CssPosition.js',
			'ext-6.2.0.940/packages/core/src/util/Translatable.js',
			'ext-6.2.0.940/modern/modern/src/behavior/Translatable.js',
			'ext-6.2.0.940/modern/modern/overrides/Widget.js',
			'ext-6.2.0.940/packages/core/src/mixin/Keyboard.js',
			'ext-6.2.0.940/packages/core/src/util/Format.js',
			'ext-6.2.0.940/packages/core/src/Template.js',
			'ext-6.2.0.940/packages/core/src/util/XTemplateParser.js',
			'ext-6.2.0.940/packages/core/src/util/XTemplateCompiler.js',
			'ext-6.2.0.940/packages/core/src/XTemplate.js',
			'ext-6.2.0.940/packages/core/src/util/CSS.js',
			'ext-6.2.0.940/packages/core/src/scroll/Scroller.js',
			'ext-6.2.0.940/modern/modern/src/Component.js',
			'ext-6.2.0.940/packages/core/src/ProgressBase.js',
			'ext-6.2.0.940/packages/core/src/Progress.js',
			'ext-6.2.0.940/modern/modern/overrides/Progress.js',
			'ext-6.2.0.940/packages/core/src/app/EventDomain.js',
			'ext-6.2.0.940/packages/core/src/app/domain/Component.js',
			'ext-6.2.0.940/packages/core/src/app/EventBus.js',
			'ext-6.2.0.940/packages/core/src/app/domain/Global.js',
			'ext-6.2.0.940/packages/core/src/app/BaseController.js',
			'ext-6.2.0.940/packages/core/src/app/Util.js',
			'ext-6.2.0.940/packages/core/src/util/Filter.js',
			'ext-6.2.0.940/packages/core/src/util/Observable.js',
			'ext-6.2.0.940/packages/core/src/util/AbstractMixedCollection.js',
			'ext-6.2.0.940/packages/core/src/util/Sorter.js',
			'ext-6.2.0.940/packages/core/src/util/Sortable.js',
			'ext-6.2.0.940/packages/core/src/util/MixedCollection.js',
			'ext-6.2.0.940/packages/core/src/util/CollectionKey.js',
			'ext-6.2.0.940/packages/core/src/util/Grouper.js',
			'ext-6.2.0.940/packages/core/src/util/Collection.js',
			'ext-6.2.0.940/packages/core/src/util/ObjectTemplate.js',
			'ext-6.2.0.940/packages/core/src/data/schema/Role.js',
			'ext-6.2.0.940/packages/core/src/data/schema/Association.js',
			'ext-6.2.0.940/packages/core/src/data/schema/OneToOne.js',
			'ext-6.2.0.940/packages/core/src/data/schema/ManyToOne.js',
			'ext-6.2.0.940/packages/core/src/data/schema/ManyToMany.js',
			'ext-6.2.0.940/packages/core/src/util/Inflector.js',
			'ext-6.2.0.940/packages/core/src/data/schema/Namer.js',
			'ext-6.2.0.940/packages/core/src/data/schema/Schema.js',
			'ext-6.2.0.940/packages/core/src/data/AbstractStore.js',
			'ext-6.2.0.940/packages/core/src/data/Error.js',
			'ext-6.2.0.940/packages/core/src/data/ErrorCollection.js',
			'ext-6.2.0.940/packages/core/src/data/operation/Operation.js',
			'ext-6.2.0.940/packages/core/src/data/operation/Create.js',
			'ext-6.2.0.940/packages/core/src/data/operation/Destroy.js',
			'ext-6.2.0.940/packages/core/src/data/operation/Read.js',
			'ext-6.2.0.940/packages/core/src/data/operation/Update.js',
			'ext-6.2.0.940/packages/core/src/data/SortTypes.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Validator.js',
			'ext-6.2.0.940/packages/core/src/data/field/Field.js',
			'ext-6.2.0.940/packages/core/src/data/field/Boolean.js',
			'ext-6.2.0.940/packages/core/src/data/field/Date.js',
			'ext-6.2.0.940/packages/core/src/data/field/Integer.js',
			'ext-6.2.0.940/packages/core/src/data/field/Number.js',
			'ext-6.2.0.940/packages/core/src/data/field/String.js',
			'ext-6.2.0.940/packages/core/src/data/identifier/Generator.js',
			'ext-6.2.0.940/packages/core/src/data/identifier/Sequential.js',
			'ext-6.2.0.940/packages/core/src/data/Model.js',
			'ext-6.2.0.940/packages/core/src/data/ResultSet.js',
			'ext-6.2.0.940/packages/core/src/data/reader/Reader.js',
			'ext-6.2.0.940/packages/core/src/data/writer/Writer.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Proxy.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Client.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Memory.js',
			'ext-6.2.0.940/packages/core/src/data/ProxyStore.js',
			'ext-6.2.0.940/packages/core/src/data/LocalStore.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Server.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Ajax.js',
			'ext-6.2.0.940/packages/core/src/data/reader/Json.js',
			'ext-6.2.0.940/packages/core/src/data/writer/Json.js',
			'ext-6.2.0.940/packages/core/src/util/Group.js',
			'ext-6.2.0.940/packages/core/src/util/SorterCollection.js',
			'ext-6.2.0.940/packages/core/src/util/FilterCollection.js',
			'ext-6.2.0.940/packages/core/src/util/GroupCollection.js',
			'ext-6.2.0.940/packages/core/src/data/Store.js',
			'ext-6.2.0.940/packages/core/src/data/reader/Array.js',
			'ext-6.2.0.940/packages/core/src/data/ArrayStore.js',
			'ext-6.2.0.940/packages/core/src/data/StoreManager.js',
			'ext-6.2.0.940/packages/core/src/app/domain/Store.js',

			// 'ext-6.2.0.940/packages/core/src/app/route/Queue.js',
			// 'ext-6.2.0.940/packages/core/src/app/route/Route.js',
			// 'ext-6.2.0.940/packages/core/src/util/History.js',
			// 'ext-6.2.0.940/packages/core/src/app/route/Router.js',
			// 'ext-6.2.0.940/packages/core/src/app/Controller.js',
			// 'ext-6.2.0.940/packages/core/src/app/Application.js',

			'ext-6.2.0.940/packages/core/overrides/app/Application.js',
			'ext-6.2.0.940/packages/core/src/util/ItemCollection.js',
			'ext-6.2.0.940/packages/core/src/mixin/Queryable.js',
			'ext-6.2.0.940/packages/core/src/mixin/Container.js',
			'ext-6.2.0.940/modern/modern/src/Container.js',
			'ext-6.2.0.940/modern/modern/src/util/InputBlocker.js',
			'ext-6.2.0.940/modern/modern/src/Mask.js',
			'ext-6.2.0.940/modern/modern/src/LoadMask.js',
			'ext-6.2.0.940/modern/modern/src/layout/Abstract.js',
			'ext-6.2.0.940/packages/core/src/mixin/Hookable.js',
			'ext-6.2.0.940/modern/modern/src/util/Wrapper.js',
			'ext-6.2.0.940/modern/modern/src/layout/wrapper/BoxDock.js',
			'ext-6.2.0.940/modern/modern/src/layout/wrapper/Inner.js',
			'ext-6.2.0.940/modern/modern/src/layout/Default.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Abstract.js',
			'ext-6.2.0.940/packages/core/src/fx/State.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Abstract.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Slide.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/SlideOut.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Fade.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/FadeOut.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Flip.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Pop.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/PopOut.js',
			'ext-6.2.0.940/packages/core/src/fx/Animation.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Style.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Slide.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Cover.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Reveal.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Fade.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Flip.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Pop.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Scroll.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/Card.js',
			'ext-6.2.0.940/modern/modern/src/layout/Card.js',

			// 'ext-6.2.0.940/modern/modern/src/viewport/Default.js',
			// 'ext-6.2.0.940/modern/modern/src/viewport/Ios.js',
			// 'ext-6.2.0.940/modern/modern/src/viewport/Android.js',
			// 'ext-6.2.0.940/modern/modern/src/viewport/WindowsPhone.js',
			// 'ext-6.2.0.940/modern/modern/src/viewport/Viewport.js',
			// 'ext-6.2.0.940/modern/modern/overrides/app/Application.js',
			// 'ext-6.2.0.940/packages/core/src/app/Profile.js',
			// 'ext-6.2.0.940/packages/core/src/app/domain/View.js',
			// 'ext-6.2.0.940/packages/core/src/app/ViewController.js',

			'ext-6.2.0.940/packages/core/src/util/Bag.js',
			'ext-6.2.0.940/packages/core/src/util/Scheduler.js',
			'ext-6.2.0.940/packages/core/src/data/Batch.js',
			'ext-6.2.0.940/packages/core/src/data/matrix/Slice.js',
			'ext-6.2.0.940/packages/core/src/data/matrix/Side.js',
			'ext-6.2.0.940/packages/core/src/data/matrix/Matrix.js',
			'ext-6.2.0.940/packages/core/src/data/session/ChangesVisitor.js',
			'ext-6.2.0.940/packages/core/src/data/session/ChildChangesVisitor.js',
			'ext-6.2.0.940/packages/core/src/data/session/BatchVisitor.js',
			'ext-6.2.0.940/packages/core/src/mixin/Dirty.js',
			'ext-6.2.0.940/packages/core/src/data/Session.js',
			'ext-6.2.0.940/packages/core/src/util/Schedulable.js',
			'ext-6.2.0.940/packages/core/src/app/bind/BaseBinding.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Binding.js',
			'ext-6.2.0.940/packages/core/src/app/bind/AbstractStub.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Stub.js',
			'ext-6.2.0.940/packages/core/src/app/bind/LinkStub.js',
			'ext-6.2.0.940/packages/core/src/app/bind/RootStub.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Multi.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Formula.js',
			'ext-6.2.0.940/packages/core/src/util/Fly.js',
			'ext-6.2.0.940/packages/core/src/parse/Tokenizer.js',
			'ext-6.2.0.940/packages/core/src/parse/Symbol.js',
			'ext-6.2.0.940/packages/core/src/parse/symbol/Constant.js',
			'ext-6.2.0.940/packages/core/src/parse/symbol/Infix.js',
			'ext-6.2.0.940/packages/core/src/parse/symbol/InfixRight.js',
			'ext-6.2.0.940/packages/core/src/parse/symbol/Paren.js',
			'ext-6.2.0.940/packages/core/src/parse/symbol/Prefix.js',
			'ext-6.2.0.940/packages/core/src/parse/Parser.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Parser.js',
			'ext-6.2.0.940/packages/core/src/app/bind/Template.js',
			'ext-6.2.0.940/packages/core/src/app/bind/TemplateBinding.js',
			'ext-6.2.0.940/packages/core/src/data/ChainedStore.js',
			'ext-6.2.0.940/packages/core/src/app/ViewModel.js',
			'ext-6.2.0.940/packages/core/src/app/domain/Controller.js',
			'ext-6.2.0.940/packages/core/src/direct/Manager.js',
			'ext-6.2.0.940/packages/core/src/direct/Provider.js',
			'ext-6.2.0.940/packages/core/src/app/domain/Direct.js',
			'ext-6.2.0.940/packages/core/src/data/PageMap.js',
			'ext-6.2.0.940/packages/core/src/data/BufferedStore.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Direct.js',
			'ext-6.2.0.940/packages/core/src/data/DirectStore.js',
			'ext-6.2.0.940/packages/core/src/data/JsonP.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/JsonP.js',
			'ext-6.2.0.940/packages/core/src/data/JsonPStore.js',
			'ext-6.2.0.940/packages/core/src/data/JsonStore.js',
			'ext-6.2.0.940/packages/core/src/data/ModelManager.js',
			'ext-6.2.0.940/packages/core/src/data/NodeInterface.js',
			'ext-6.2.0.940/packages/core/src/data/TreeModel.js',
			'ext-6.2.0.940/packages/core/src/data/NodeStore.js',
			'ext-6.2.0.940/packages/core/src/data/Request.js',
			'ext-6.2.0.940/packages/core/src/data/TreeStore.js',
			'ext-6.2.0.940/packages/core/src/data/Types.js',
			'ext-6.2.0.940/packages/core/src/data/Validation.js',
			'ext-6.2.0.940/packages/core/src/dom/Helper.js',
			'ext-6.2.0.940/packages/core/src/dom/Query.js',
			'ext-6.2.0.940/packages/core/src/data/reader/Xml.js',
			'ext-6.2.0.940/packages/core/src/data/writer/Xml.js',
			'ext-6.2.0.940/packages/core/src/data/XmlStore.js',
			'ext-6.2.0.940/packages/core/src/data/identifier/Negative.js',
			'ext-6.2.0.940/packages/core/src/data/identifier/Uuid.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/WebStorage.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/LocalStorage.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/Rest.js',
			'ext-6.2.0.940/packages/core/src/data/proxy/SessionStorage.js',
			'ext-6.2.0.940/packages/core/src/data/schema/BelongsTo.js',
			'ext-6.2.0.940/packages/core/src/data/schema/HasMany.js',
			'ext-6.2.0.940/packages/core/src/data/schema/HasOne.js',
			'ext-6.2.0.940/packages/core/src/data/schema/Reference.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Bound.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Format.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Email.js',
			'ext-6.2.0.940/packages/core/src/data/validator/List.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Exclusion.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Inclusion.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Length.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Presence.js',
			'ext-6.2.0.940/packages/core/src/data/validator/Range.js',

			// 'ext-6.2.0.940/packages/core/src/direct/Event.js',
			// 'ext-6.2.0.940/packages/core/src/direct/RemotingEvent.js',
			// 'ext-6.2.0.940/packages/core/src/direct/ExceptionEvent.js',
			// 'ext-6.2.0.940/packages/core/src/direct/JsonProvider.js',

			'ext-6.2.0.940/packages/core/src/util/TaskRunner.js',

			// 'ext-6.2.0.940/packages/core/src/direct/PollingProvider.js',
			// 'ext-6.2.0.940/packages/core/src/direct/RemotingMethod.js',
			// 'ext-6.2.0.940/packages/core/src/direct/Transaction.js',
			// 'ext-6.2.0.940/packages/core/src/direct/RemotingProvider.js',

			'ext-6.2.0.940/packages/core/src/dom/Fly.js',
			'ext-6.2.0.940/packages/core/src/dom/CompositeElementLite.js',
			'ext-6.2.0.940/packages/core/src/dom/CompositeElement.js',
			'ext-6.2.0.940/packages/core/src/dom/GarbageCollector.js',
			'ext-6.2.0.940/packages/core/src/dom/TouchAction.js',
			'ext-6.2.0.940/packages/core/src/drag/Constraint.js',
			'ext-6.2.0.940/packages/core/src/drag/Info.js',
			'ext-6.2.0.940/packages/core/src/drag/Item.js',
			'ext-6.2.0.940/packages/core/src/drag/Manager.js',
			'ext-6.2.0.940/packages/core/src/drag/Source.js',
			'ext-6.2.0.940/packages/core/src/drag/Target.js',
			'ext-6.2.0.940/packages/core/src/drag/proxy/None.js',
			'ext-6.2.0.940/packages/core/src/drag/proxy/Original.js',
			'ext-6.2.0.940/packages/core/src/drag/proxy/Placeholder.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Recognizer.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/SingleTouch.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/DoubleTap.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Drag.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Swipe.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/EdgeSwipe.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/LongPress.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/MultiTouch.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Pinch.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Rotate.js',
			'ext-6.2.0.940/packages/core/src/event/gesture/Tap.js',
			'ext-6.2.0.940/packages/core/src/event/publisher/Focus.js',
			'ext-6.2.0.940/packages/core/src/fx/runner/Css.js',
			'ext-6.2.0.940/packages/core/src/fx/runner/CssTransition.js',
			'ext-6.2.0.940/packages/core/src/fx/Runner.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Cube.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/Wipe.js',
			'ext-6.2.0.940/packages/core/src/fx/animation/WipeOut.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/Bounce.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/Momentum.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/BoundMomentum.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/EaseIn.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/EaseOut.js',
			'ext-6.2.0.940/packages/core/src/fx/easing/Easing.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/Cube.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/ScrollCover.js',
			'ext-6.2.0.940/packages/core/src/fx/layout/card/ScrollReveal.js',
			'ext-6.2.0.940/packages/core/src/fx/runner/CssAnimation.js',
			'ext-6.2.0.940/packages/core/src/list/AbstractTreeItem.js',
			'ext-6.2.0.940/packages/core/src/list/RootTreeItem.js',
			'ext-6.2.0.940/packages/core/src/list/TreeItem.js',
			'ext-6.2.0.940/modern/modern/overrides/list/TreeItem.js',
			'ext-6.2.0.940/packages/core/src/list/Tree.js',
			'ext-6.2.0.940/modern/modern/overrides/list/Tree.js',
			'ext-6.2.0.940/packages/core/src/mixin/Accessible.js',
			'ext-6.2.0.940/packages/core/src/mixin/ConfigState.js',
			'ext-6.2.0.940/packages/core/src/mixin/Mashup.js',
			'ext-6.2.0.940/packages/core/src/mixin/Responsive.js',
			'ext-6.2.0.940/packages/core/src/mixin/Selectable.js',
			'ext-6.2.0.940/packages/core/src/mixin/StyleCacher.js',
			'ext-6.2.0.940/packages/core/src/perf/Accumulator.js',
			'ext-6.2.0.940/packages/core/src/perf/Monitor.js',
			'ext-6.2.0.940/packages/core/src/plugin/Abstract.js',
			'ext-6.2.0.940/packages/core/src/plugin/LazyItems.js',
			'ext-6.2.0.940/packages/core/src/plugin/MousEnter.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Shape.js',
			'ext-6.2.0.940/packages/core/src/sparkline/CanvasBase.js',
			'ext-6.2.0.940/packages/core/src/sparkline/CanvasCanvas.js',
			'ext-6.2.0.940/packages/core/src/sparkline/VmlCanvas.js',
			'ext-6.2.0.940/packages/core/src/util/Color.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Base.js',
			'ext-6.2.0.940/modern/modern/overrides/sparkline/Base.js',
			'ext-6.2.0.940/packages/core/src/sparkline/BarBase.js',
			'ext-6.2.0.940/packages/core/src/sparkline/RangeMap.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Bar.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Box.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Bullet.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Discrete.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Line.js',
			'ext-6.2.0.940/packages/core/src/sparkline/Pie.js',
			'ext-6.2.0.940/packages/core/src/sparkline/TriState.js',
			'ext-6.2.0.940/packages/core/src/util/Base64.js',
			'ext-6.2.0.940/packages/core/src/util/DelimitedValue.js',
			'ext-6.2.0.940/packages/core/src/util/CSV.js',
			'ext-6.2.0.940/packages/core/src/util/LocalStorage.js',
			'ext-6.2.0.940/packages/core/src/util/TSV.js',
			'ext-6.2.0.940/packages/core/src/util/TaskManager.js',
			'ext-6.2.0.940/packages/core/src/util/TextMetrics.js',
			'ext-6.2.0.940/packages/core/src/util/paintmonitor/OverflowChange.js',
			'ext-6.2.0.940/modern/modern/src/AbstractComponent.js',
			'ext-6.2.0.940/modern/modern/src/Panel.js',
			'ext-6.2.0.940/modern/modern/src/Sheet.js',
			'ext-6.2.0.940/modern/modern/src/ActionSheet.js',
			'ext-6.2.0.940/modern/modern/src/Anim.js',
			'ext-6.2.0.940/modern/modern/src/Media.js',
			'ext-6.2.0.940/modern/modern/src/Audio.js',
			'ext-6.2.0.940/modern/modern/src/Button.js',
			'ext-6.2.0.940/modern/modern/src/Decorator.js',
			'ext-6.2.0.940/modern/modern/src/Img.js',
			'ext-6.2.0.940/modern/modern/src/Label.js',
			'ext-6.2.0.940/modern/modern/src/Menu.js',
			'ext-6.2.0.940/modern/modern/src/field/Input.js',
			'ext-6.2.0.940/modern/modern/src/field/Field.js',
			'ext-6.2.0.940/modern/modern/src/field/TextInput.js',
			'ext-6.2.0.940/modern/modern/src/field/Text.js',
			'ext-6.2.0.940/modern/modern/src/field/TextAreaInput.js',
			'ext-6.2.0.940/modern/modern/src/field/TextArea.js',
			'ext-6.2.0.940/modern/modern/src/layout/Box.js',
			'ext-6.2.0.940/modern/modern/src/layout/FlexBox.js',
			'ext-6.2.0.940/modern/modern/src/layout/VBox.js',
			'ext-6.2.0.940/modern/modern/src/MessageBox.js',
			'ext-6.2.0.940/modern/modern/src/SegmentedButton.js',
			'ext-6.2.0.940/modern/modern/src/util/Draggable.js',
			'ext-6.2.0.940/modern/modern/src/Sortable.js',
			'ext-6.2.0.940/modern/modern/src/Spacer.js',
			'ext-6.2.0.940/modern/modern/src/Title.js',
			'ext-6.2.0.940/modern/modern/src/TitleBar.js',
			'ext-6.2.0.940/modern/theme-neptune/overrides/Titlebar.js',
			'ext-6.2.0.940/modern/modern/src/Toast.js',
			'ext-6.2.0.940/modern/modern/src/layout/HBox.js',
			'ext-6.2.0.940/modern/modern/src/Toolbar.js',
			'ext-6.2.0.940/modern/modern/src/Video.js',
			'ext-6.2.0.940/modern/modern/src/behavior/Draggable.js',
			'ext-6.2.0.940/modern/modern/src/behavior/Droppable.js',
			'ext-6.2.0.940/modern/modern/src/behavior/Sortable.js',
			'ext-6.2.0.940/modern/modern/src/carousel/Item.js',
			'ext-6.2.0.940/modern/modern/src/carousel/Indicator.js',
			'ext-6.2.0.940/modern/modern/src/util/TranslatableGroup.js',
			'ext-6.2.0.940/modern/modern/src/carousel/Carousel.js',
			'ext-6.2.0.940/modern/modern/src/carousel/Infinite.js',
			'ext-6.2.0.940/modern/modern/src/dataview/component/DataItem.js',
			'ext-6.2.0.940/modern/modern/src/dataview/component/Container.js',
			'ext-6.2.0.940/modern/modern/src/dataview/element/Container.js',
			'ext-6.2.0.940/modern/modern/src/dataview/DataView.js',
			'ext-6.2.0.940/modern/modern/src/dataview/IndexBar.js',
			'ext-6.2.0.940/modern/modern/src/dataview/ItemHeader.js',
			'ext-6.2.0.940/modern/modern/src/dataview/ListItemBody.js',
			'ext-6.2.0.940/modern/modern/src/dataview/ListItemDisclosure.js',
			'ext-6.2.0.940/modern/modern/src/dataview/ListItem.js',
			'ext-6.2.0.940/modern/modern/src/dataview/SimpleListItem.js',
			'ext-6.2.0.940/modern/modern/src/util/PositionMap.js',
			'ext-6.2.0.940/modern/modern/src/dataview/List.js',
			'ext-6.2.0.940/modern/modern/src/dataview/NestedList.js',
			'ext-6.2.0.940/modern/modern/src/dataview/element/List.js',
			'ext-6.2.0.940/modern/modern/src/tip/ToolTip.js',
			'ext-6.2.0.940/modern/theme-neptune/overrides/tip/ToolTip.js',
			'ext-6.2.0.940/modern/modern/src/dataview/plugin/ItemTip.js',
			'ext-6.2.0.940/modern/modern/src/field/CheckboxInput.js',
			'ext-6.2.0.940/modern/modern/src/field/Checkbox.js',
			'ext-6.2.0.940/modern/modern/src/field/Picker.js',
			'ext-6.2.0.940/modern/modern/src/picker/Slot.js',
			'ext-6.2.0.940/modern/modern/src/picker/Picker.js',
			'ext-6.2.0.940/modern/modern/src/picker/Date.js',
			'ext-6.2.0.940/modern/modern/src/field/DatePicker.js',
			'ext-6.2.0.940/modern/modern/src/field/DatePickerNative.js',
			'ext-6.2.0.940/modern/modern/src/field/Email.js',
			'ext-6.2.0.940/modern/modern/src/field/FileInput.js',
			'ext-6.2.0.940/modern/modern/src/field/File.js',
			'ext-6.2.0.940/modern/modern/src/field/Hidden.js',
			'ext-6.2.0.940/modern/modern/src/field/Number.js',
			'ext-6.2.0.940/modern/modern/src/field/PasswordInput.js',
			'ext-6.2.0.940/modern/modern/src/field/Password.js',
			'ext-6.2.0.940/modern/modern/src/field/RadioInput.js',
			'ext-6.2.0.940/modern/modern/src/field/Radio.js',
			'ext-6.2.0.940/modern/modern/src/field/Search.js',
			'ext-6.2.0.940/modern/modern/src/field/Select.js',
			'ext-6.2.0.940/modern/modern/src/slider/Thumb.js',
			'ext-6.2.0.940/modern/modern/src/slider/Slider.js',
			'ext-6.2.0.940/modern/modern/src/field/Slider.js',
			'ext-6.2.0.940/modern/modern/src/field/SingleSlider.js',
			'ext-6.2.0.940/modern/modern/src/field/Spinner.js',
			'ext-6.2.0.940/modern/modern/src/slider/Toggle.js',
			'ext-6.2.0.940/modern/modern/src/field/Toggle.js',
			'ext-6.2.0.940/modern/modern/src/field/Url.js',
			'ext-6.2.0.940/modern/modern/src/util/TapRepeater.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Trigger.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Clear.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Date.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Expand.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Reveal.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/Search.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/SpinDown.js',
			'ext-6.2.0.940/modern/modern/src/field/trigger/SpinUp.js',
			'ext-6.2.0.940/modern/modern/src/form/FieldContainer.js',
			'ext-6.2.0.940/modern/modern/src/form/FieldSet.js',
			'ext-6.2.0.940/modern/modern/src/form/Panel.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Base.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Text.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Cell.js',
			'ext-6.2.0.940/modern/modern/src/grid/RowBody.js',
			'ext-6.2.0.940/modern/modern/src/grid/RowHeader.js',
			'ext-6.2.0.940/modern/modern/src/grid/Row.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Summary.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Column.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Date.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Date.js',
			'ext-6.2.0.940/modern/modern/src/grid/HeaderContainer.js',
			'ext-6.2.0.940/modern/modern/src/grid/HeaderGroup.js',
			'ext-6.2.0.940/modern/modern/src/grid/Grid.js',
			'ext-6.2.0.940/modern/modern/src/grid/PagingToolbar.js',
			'ext-6.2.0.940/modern/modern/src/grid/Tree.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Boolean.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Check.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Expander.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Number.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/RowNumberer.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Tree.js',
			'ext-6.2.0.940/modern/modern/src/grid/cell/Widget.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Boolean.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Check.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Number.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/RowNumberer.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Selection.js',
			'ext-6.2.0.940/modern/modern/src/grid/column/Tree.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/ColumnResizing.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/Editable.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/MultiSelection.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/PagingToolbar.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/RowExpander.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/SummaryRow.js',
			'ext-6.2.0.940/modern/modern/src/plugin/SortableList.js',
			'ext-6.2.0.940/modern/modern/src/layout/Fit.js',
			'ext-6.2.0.940/modern/modern/src/grid/plugin/ViewOptions.js',
			'ext-6.2.0.940/modern/modern/src/layout/Float.js',
			'ext-6.2.0.940/modern/modern/src/layout/wrapper/Dock.js',
			'ext-6.2.0.940/modern/modern/src/mixin/Progressable.js',
			'ext-6.2.0.940/modern/modern/src/navigation/Bar.js',
			'ext-6.2.0.940/modern/modern/src/navigation/View.js',
			'ext-6.2.0.940/modern/modern/src/panel/Header.js',
			'ext-6.2.0.940/modern/modern/src/panel/Title.js',
			'ext-6.2.0.940/modern/modern/src/panel/Tool.js',
			'ext-6.2.0.940/modern/modern/src/plugin/ListPaging.js',
			'ext-6.2.0.940/modern/modern/src/plugin/PullRefresh.js',
			'ext-6.2.0.940/modern/modern/src/plugin/Responsive.js',
			'ext-6.2.0.940/modern/modern/src/plugin/field/PlaceHolderLabel.js',
			'ext-6.2.0.940/modern/modern/src/tab/Tab.js',
			'ext-6.2.0.940/modern/modern/src/tab/Bar.js',
			'ext-6.2.0.940/modern/modern/src/tab/Panel.js',
			'ext-6.2.0.940/modern/modern/src/table/Cell.js',
			'ext-6.2.0.940/modern/modern/src/table/Row.js',
			'ext-6.2.0.940/modern/modern/src/table/Table.js',
			'ext-6.2.0.940/modern/modern/src/tip/Manager.js',
			'ext-6.2.0.940/modern/modern/src/util/Audio.js',
			'ext-6.2.0.940/modern/modern/src/util/BufferedCollection.js',
			'ext-6.2.0.940/modern/modern/src/util/Droppable.js',
			'ext-6.2.0.940/modern/modern/src/util/Geolocation.js',
			'ext-6.2.0.940/modern/modern/src/util/LineSegment.js',
			'ext-6.2.0.940/modern/modern/src/util/TranslatableList.js',
			'ext-6.2.0.940/modern/theme-neptune/overrides/init.js',
			'ext-6.2.0.940/modern/theme-triton/overrides/init.js'
		])
		.pipe(concat('allmjg.js'))
		.pipe(gulp.dest('dist'))
		.pipe(rename('allmjg.min.js'))
		.pipe(uglify())
		.pipe(gulp.dest('dist/js'));
});


// Watch Files For Changes
gulp.task('watch', function() {
    gulp.watch('js/*.js', ['lint', 'scripts']);
    gulp.watch('scss/*.scss', ['sass']);
});

// Default Task
gulp.task('default', ['lint', 'sass', 'scripts', 'watch']);